version: '3'

services:
  database:
    image: 'postgres:latest'
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:

    # - POSTGRES_HOST_AUTH_METHOD=trust
    -  POSTGRES_PASSWORD:"superpassword"
    ports:
      - 5432:5432
    # env_file:
    #   - .env
    # networks:
    #   - postgres-network
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ${PWD}/db-data/:/var/lib/postgresql/data/
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres:
    driver: local
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 15433:80
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #   networks:
  #     - postgres-network
  #   volumes:
  #     - ${PWD}/pgadmin-data/:/var/lib/pgadmin/

# networks: 
#   postgres-network:
#     driver: bridge