@url = http://localhost:5000
@reservationId = 19ac8d99-bd91-4ed2-919b-feebe8ca13ff
@parkingSpotId = 00000000-0000-0000-0000-000000000001


###
GET {{url}}

###
GET {{url}}/reservations
###
GET {{url}}/reservations/{{reservationId}}


###
POST {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "employeeName": "John Doe",
    "licensePlate": "XYZ123",
    "date": "2025-02-23"
}

###
PUT  {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZ127"
}

###
DELETE  {{url}}/reservations/{{reservationId}}